import { z } from "zod";

export const shipmentPartySchema = z.object({
  name: z.string().trim().min(1).max(200),
  contact_person: z.string().trim().max(120).nullable().optional(),
  mobile: z.string().trim().max(30).nullable().optional(),
  email: z.string().trim().email().max(200).nullable().optional(),
  address: z.string().trim().max(500).nullable().optional(),
  city: z.string().trim().max(120).nullable().optional(),
  state: z.string().trim().max(120).nullable().optional(),
  country: z.string().trim().max(120).nullable().optional(),
  postal_code: z.string().trim().max(30).nullable().optional(),
  tax_id: z.string().trim().max(40).nullable().optional(),
});

export const shipmentEwaySchema = z.object({
  eway_bill_number: z.string().trim().max(40).nullable().optional(),
  eway_bill_date: z.string().trim().max(40).nullable().optional(),
  eway_validity: z.string().trim().max(40).nullable().optional(),
  transporter_id: z.string().trim().max(40).nullable().optional(),
  vehicle_number: z.string().trim().max(30).nullable().optional(),
  lr_number: z.string().trim().max(40).nullable().optional(),
  delivery_challan_number: z.string().trim().max(40).nullable().optional(),
});

export const shipmentCrossBorderSchema = z.object({
  exporter_of_record: z.string().trim().max(200).nullable().optional(),
  importer_of_record: z.string().trim().max(200).nullable().optional(),
  iec_number: z.string().trim().max(40).nullable().optional(),
  origin_country: z.string().trim().max(120).nullable().optional(),
  destination_country: z.string().trim().max(120).nullable().optional(),
  incoterms: z.string().trim().max(20).nullable().optional(),
  port_of_loading: z.string().trim().max(120).nullable().optional(),
  port_of_discharge: z.string().trim().max(120).nullable().optional(),
  final_destination: z.string().trim().max(200).nullable().optional(),
  commercial_invoice_number: z.string().trim().max(60).nullable().optional(),
  packing_list_number: z.string().trim().max(60).nullable().optional(),
  shipping_bill_number: z.string().trim().max(60).nullable().optional(),
  bill_of_entry_number: z.string().trim().max(60).nullable().optional(),
  bl_awb_number: z.string().trim().max(60).nullable().optional(),
  certificate_of_origin: z.boolean().optional(),
  customs_broker: z.string().trim().max(200).nullable().optional(),
  customs_status: z.string().trim().max(120).nullable().optional(),
  duty_tax_amount: z.number().min(0).optional(),
  seal_number: z.string().trim().max(40).nullable().optional(),
});

export const createShipmentSchema = z.object({
  shipment_type: z.enum(["inbound", "outbound", "transfer", "return"]),
  linked_doc_type: z.enum(["goods_purchase_order", "purchase_invoice", "sales_invoice", "goods_dispatch", "manual"]).optional(),
  linked_doc_id: z.string().trim().max(200).nullable().optional(),
  priority: z.enum(["normal", "urgent", "critical"]).optional(),
  owner_id: z.string().trim().max(200).nullable().optional(),
  business_unit: z.string().trim().max(120).nullable().optional(),
  sales_channel: z.string().trim().max(120).nullable().optional(),
  pickup: shipmentPartySchema.partial({ name: true }).optional(),
  pickup_window: z.string().trim().max(120).nullable().optional(),
  delivery: shipmentPartySchema.partial({ name: true }).optional(),
  requested_delivery_date: z.string().trim().max(40).nullable().optional(),
  mode: z.enum(["road", "air", "sea", "rail", "courier"]).optional(),
  service_type: z.enum(["standard", "express", "surface", "air", "freight", "container"]).optional(),
  border: z.enum(["domestic", "cross_border"]).optional(),
  package_count: z.number().min(0).optional(),
  actual_weight: z.number().min(0).optional(),
  volumetric_weight: z.number().min(0).optional(),
  length_cm: z.number().min(0).nullable().optional(),
  width_cm: z.number().min(0).nullable().optional(),
  height_cm: z.number().min(0).nullable().optional(),
  package_unit: z.string().trim().max(40).nullable().optional(),
  package_unit_count: z.number().min(0).optional(),
  declared_value: z.number().min(0).optional(),
  currency: z.string().trim().max(10).optional(),
  goods_description: z.string().trim().max(1000).nullable().optional(),
  hs_code: z.string().trim().max(30).nullable().optional(),
  dangerous_goods: z.boolean().optional(),
  insurance_required: z.boolean().optional(),
  handling_notes: z.string().trim().max(1000).nullable().optional(),
  freight_payment: z.enum(["prepaid", "to_pay", "collect", "third_party"]).optional(),
  estimated_freight: z.number().min(0).optional(),
  cost_centre: z.string().trim().max(120).nullable().optional(),
  eway: shipmentEwaySchema.optional(),
  cross_border: shipmentCrossBorderSchema.optional(),
});

export const manualBookingSchema = z.object({
  provider_id: z.string().trim().max(200).nullable().optional(),
  carrier_name: z.string().trim().min(1).max(200),
  service_level: z.string().trim().max(120).nullable().optional(),
  tracking_number: z.string().trim().min(1).max(120),
  booked_freight: z.number().min(0),
  fuel_surcharge: z.number().min(0).optional(),
  insurance_charge: z.number().min(0).optional(),
  other_charges: z.number().min(0).optional(),
  vehicle_number: z.string().trim().max(30).nullable().optional(),
  driver_name: z.string().trim().max(120).nullable().optional(),
  driver_mobile: z.string().trim().max(30).nullable().optional(),
  transporter_id: z.string().trim().max(40).nullable().optional(),
  expected_pickup_date: z.string().trim().max(40).nullable().optional(),
  expected_delivery_date: z.string().trim().max(40).nullable().optional(),
});

export const manualQuoteSchema = z.object({
  provider_id: z.string().trim().max(200).nullable().optional(),
  provider_name: z.string().trim().min(1).max(200),
  carrier_name: z.string().trim().max(200).nullable().optional(),
  mode: z.enum(["road", "air", "sea", "rail", "courier"]).optional(),
  service_level: z.string().trim().max(120).nullable().optional(),
  estimated_pickup_date: z.string().trim().max(40).nullable().optional(),
  estimated_delivery_date: z.string().trim().max(40).nullable().optional(),
  transit_days: z.number().min(0).nullable().optional(),
  freight_charge: z.number().min(0),
  fuel_charges: z.number().min(0).optional(),
  other_charges: z.number().min(0).optional(),
  insurance_charge: z.number().min(0).optional(),
  tracking_available: z.boolean().optional(),
  cancellation_terms: z.string().trim().max(500).nullable().optional(),
});

export const manualEventSchema = z.object({
  status: z.enum([
    "draft", "quote_requested", "quote_received", "booked", "pickup_scheduled",
    "picked_up", "in_transit", "at_hub", "at_customs", "customs_hold",
    "out_for_delivery", "delivered", "delivery_attempt_failed", "delayed",
    "damaged", "lost", "return_initiated", "returned", "cancelled",
  ]),
  carrier_raw_status: z.string().trim().max(300).nullable().optional(),
  event_at: z.string().trim().max(40).optional(),
  location: z.string().trim().max(200).nullable().optional(),
  description: z.string().trim().max(1000).nullable().optional(),
});

export const providerSchema = z.object({
  provider_name: z.string().trim().min(1).max(200),
  carrier_name: z.string().trim().max(200).nullable().optional(),
  modes: z.array(z.enum(["road", "air", "sea", "rail", "courier"])).min(1),
  domestic: z.boolean().optional(),
  cross_border: z.boolean().optional(),
  service_areas: z.string().trim().max(500).nullable().optional(),
  integration_status: z.enum(["manual", "integrated", "disabled"]).optional(),
  adapter_key: z.string().trim().max(60).optional(),
  account_ref: z.string().trim().max(120).nullable().optional(),
  billing_terms: z.string().trim().max(500).nullable().optional(),
  default_service_level: z.string().trim().max(120).nullable().optional(),
  insurance_option: z.boolean().optional(),
  support_contact: z.string().trim().max(200).nullable().optional(),
  escalation_contact: z.string().trim().max(200).nullable().optional(),
  active: z.boolean().optional(),
});
