/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoaTokenRouteImport } from './routes/noa.$token'
import { Route as ApprovalsTokenRouteImport } from './routes/approvals.$token'
import { Route as AppVendorsRouteImport } from './routes/app.vendors'
import { Route as AppUploadInvoiceRouteImport } from './routes/app.upload-invoice'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSalesOrdersRouteImport } from './routes/app.sales-orders'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppQuotationsRouteImport } from './routes/app.quotations'
import { Route as AppQueueRouteImport } from './routes/app.queue'
import { Route as AppPurchasesRouteImport } from './routes/app.purchases'
import { Route as AppPurchaseOrdersRouteImport } from './routes/app.purchase-orders'
import { Route as AppProformasRouteImport } from './routes/app.proformas'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppGoodsReceiptsRouteImport } from './routes/app.goods-receipts'
import { Route as AppForecastingRouteImport } from './routes/app.forecasting'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppDispatchesRouteImport } from './routes/app.dispatches'
import { Route as AppDebtorsRouteImport } from './routes/app.debtors'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCreditDebitNotesRouteImport } from './routes/app.credit-debit-notes'
import { Route as AppCheckerRouteImport } from './routes/app.checker'
import { Route as AppBulkPaymentsRouteImport } from './routes/app.bulk-payments'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppAdvancesRouteImport } from './routes/app.advances'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAccountingRouteImport } from './routes/app.accounting'
import { Route as AppReportsIndexRouteImport } from './routes/app.reports.index'
import { Route as AppReportsTabRouteImport } from './routes/app.reports.$tab'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoaTokenRoute = NoaTokenRouteImport.update({
  id: '/noa/$token',
  path: '/noa/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsTokenRoute = ApprovalsTokenRouteImport.update({
  id: '/approvals/$token',
  path: '/approvals/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadInvoiceRoute = AppUploadInvoiceRouteImport.update({
  id: '/upload-invoice',
  path: '/upload-invoice',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesOrdersRoute = AppSalesOrdersRouteImport.update({
  id: '/sales-orders',
  path: '/sales-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsRoute = AppQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppProformasRoute = AppProformasRouteImport.update({
  id: '/proformas',
  path: '/proformas',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppGoodsReceiptsRoute = AppGoodsReceiptsRouteImport.update({
  id: '/goods-receipts',
  path: '/goods-receipts',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastingRoute = AppForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDispatchesRoute = AppDispatchesRouteImport.update({
  id: '/dispatches',
  path: '/dispatches',
  getParentRoute: () => AppRoute,
} as any)
const AppDebtorsRoute = AppDebtorsRouteImport.update({
  id: '/debtors',
  path: '/debtors',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditDebitNotesRoute = AppCreditDebitNotesRouteImport.update({
  id: '/credit-debit-notes',
  path: '/credit-debit-notes',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckerRoute = AppCheckerRouteImport.update({
  id: '/checker',
  path: '/checker',
  getParentRoute: () => AppRoute,
} as any)
const AppBulkPaymentsRoute = AppBulkPaymentsRouteImport.update({
  id: '/bulk-payments',
  path: '/bulk-payments',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvancesRoute = AppAdvancesRouteImport.update({
  id: '/advances',
  path: '/advances',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingRoute = AppAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsTabRoute = AppReportsTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => AppReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/accounting': typeof AppAccountingRoute
  '/app/admin': typeof AppAdminRoute
  '/app/advances': typeof AppAdvancesRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/bulk-payments': typeof AppBulkPaymentsRoute
  '/app/checker': typeof AppCheckerRoute
  '/app/credit-debit-notes': typeof AppCreditDebitNotesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/debtors': typeof AppDebtorsRoute
  '/app/dispatches': typeof AppDispatchesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/forecasting': typeof AppForecastingRoute
  '/app/goods-receipts': typeof AppGoodsReceiptsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/products': typeof AppProductsRoute
  '/app/proformas': typeof AppProformasRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/purchases': typeof AppPurchasesRoute
  '/app/queue': typeof AppQueueRoute
  '/app/quotations': typeof AppQuotationsRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/sales-orders': typeof AppSalesOrdersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/upload-invoice': typeof AppUploadInvoiceRoute
  '/app/vendors': typeof AppVendorsRoute
  '/approvals/$token': typeof ApprovalsTokenRoute
  '/noa/$token': typeof NoaTokenRoute
  '/app/reports/$tab': typeof AppReportsTabRoute
  '/app/reports/': typeof AppReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/accounting': typeof AppAccountingRoute
  '/app/admin': typeof AppAdminRoute
  '/app/advances': typeof AppAdvancesRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/bulk-payments': typeof AppBulkPaymentsRoute
  '/app/checker': typeof AppCheckerRoute
  '/app/credit-debit-notes': typeof AppCreditDebitNotesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/debtors': typeof AppDebtorsRoute
  '/app/dispatches': typeof AppDispatchesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/forecasting': typeof AppForecastingRoute
  '/app/goods-receipts': typeof AppGoodsReceiptsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/products': typeof AppProductsRoute
  '/app/proformas': typeof AppProformasRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/purchases': typeof AppPurchasesRoute
  '/app/queue': typeof AppQueueRoute
  '/app/quotations': typeof AppQuotationsRoute
  '/app/sales-orders': typeof AppSalesOrdersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/upload-invoice': typeof AppUploadInvoiceRoute
  '/app/vendors': typeof AppVendorsRoute
  '/approvals/$token': typeof ApprovalsTokenRoute
  '/noa/$token': typeof NoaTokenRoute
  '/app/reports/$tab': typeof AppReportsTabRoute
  '/app/reports': typeof AppReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/accounting': typeof AppAccountingRoute
  '/app/admin': typeof AppAdminRoute
  '/app/advances': typeof AppAdvancesRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/bulk-payments': typeof AppBulkPaymentsRoute
  '/app/checker': typeof AppCheckerRoute
  '/app/credit-debit-notes': typeof AppCreditDebitNotesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/debtors': typeof AppDebtorsRoute
  '/app/dispatches': typeof AppDispatchesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/forecasting': typeof AppForecastingRoute
  '/app/goods-receipts': typeof AppGoodsReceiptsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/products': typeof AppProductsRoute
  '/app/proformas': typeof AppProformasRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/purchases': typeof AppPurchasesRoute
  '/app/queue': typeof AppQueueRoute
  '/app/quotations': typeof AppQuotationsRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/sales-orders': typeof AppSalesOrdersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/upload-invoice': typeof AppUploadInvoiceRoute
  '/app/vendors': typeof AppVendorsRoute
  '/approvals/$token': typeof ApprovalsTokenRoute
  '/noa/$token': typeof NoaTokenRoute
  '/app/reports/$tab': typeof AppReportsTabRoute
  '/app/reports/': typeof AppReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/accounting'
    | '/app/admin'
    | '/app/advances'
    | '/app/alerts'
    | '/app/bulk-payments'
    | '/app/checker'
    | '/app/credit-debit-notes'
    | '/app/dashboard'
    | '/app/debtors'
    | '/app/dispatches'
    | '/app/expenses'
    | '/app/forecasting'
    | '/app/goods-receipts'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/products'
    | '/app/proformas'
    | '/app/purchase-orders'
    | '/app/purchases'
    | '/app/queue'
    | '/app/quotations'
    | '/app/reports'
    | '/app/sales-orders'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/upload-invoice'
    | '/app/vendors'
    | '/approvals/$token'
    | '/noa/$token'
    | '/app/reports/$tab'
    | '/app/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/accounting'
    | '/app/admin'
    | '/app/advances'
    | '/app/alerts'
    | '/app/bulk-payments'
    | '/app/checker'
    | '/app/credit-debit-notes'
    | '/app/dashboard'
    | '/app/debtors'
    | '/app/dispatches'
    | '/app/expenses'
    | '/app/forecasting'
    | '/app/goods-receipts'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/products'
    | '/app/proformas'
    | '/app/purchase-orders'
    | '/app/purchases'
    | '/app/queue'
    | '/app/quotations'
    | '/app/sales-orders'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/upload-invoice'
    | '/app/vendors'
    | '/approvals/$token'
    | '/noa/$token'
    | '/app/reports/$tab'
    | '/app/reports'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/accounting'
    | '/app/admin'
    | '/app/advances'
    | '/app/alerts'
    | '/app/bulk-payments'
    | '/app/checker'
    | '/app/credit-debit-notes'
    | '/app/dashboard'
    | '/app/debtors'
    | '/app/dispatches'
    | '/app/expenses'
    | '/app/forecasting'
    | '/app/goods-receipts'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/products'
    | '/app/proformas'
    | '/app/purchase-orders'
    | '/app/purchases'
    | '/app/queue'
    | '/app/quotations'
    | '/app/reports'
    | '/app/sales-orders'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/upload-invoice'
    | '/app/vendors'
    | '/approvals/$token'
    | '/noa/$token'
    | '/app/reports/$tab'
    | '/app/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApprovalsTokenRoute: typeof ApprovalsTokenRoute
  NoaTokenRoute: typeof NoaTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noa/$token': {
      id: '/noa/$token'
      path: '/noa/$token'
      fullPath: '/noa/$token'
      preLoaderRoute: typeof NoaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals/$token': {
      id: '/approvals/$token'
      path: '/approvals/$token'
      fullPath: '/approvals/$token'
      preLoaderRoute: typeof ApprovalsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/vendors': {
      id: '/app/vendors'
      path: '/vendors'
      fullPath: '/app/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/upload-invoice': {
      id: '/app/upload-invoice'
      path: '/upload-invoice'
      fullPath: '/app/upload-invoice'
      preLoaderRoute: typeof AppUploadInvoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales-orders': {
      id: '/app/sales-orders'
      path: '/sales-orders'
      fullPath: '/app/sales-orders'
      preLoaderRoute: typeof AppSalesOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quotations': {
      id: '/app/quotations'
      path: '/quotations'
      fullPath: '/app/quotations'
      preLoaderRoute: typeof AppQuotationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/queue': {
      id: '/app/queue'
      path: '/queue'
      fullPath: '/app/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchases': {
      id: '/app/purchases'
      path: '/purchases'
      fullPath: '/app/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchase-orders': {
      id: '/app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/app/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/proformas': {
      id: '/app/proformas'
      path: '/proformas'
      fullPath: '/app/proformas'
      preLoaderRoute: typeof AppProformasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goods-receipts': {
      id: '/app/goods-receipts'
      path: '/goods-receipts'
      fullPath: '/app/goods-receipts'
      preLoaderRoute: typeof AppGoodsReceiptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forecasting': {
      id: '/app/forecasting'
      path: '/forecasting'
      fullPath: '/app/forecasting'
      preLoaderRoute: typeof AppForecastingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dispatches': {
      id: '/app/dispatches'
      path: '/dispatches'
      fullPath: '/app/dispatches'
      preLoaderRoute: typeof AppDispatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/debtors': {
      id: '/app/debtors'
      path: '/debtors'
      fullPath: '/app/debtors'
      preLoaderRoute: typeof AppDebtorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/credit-debit-notes': {
      id: '/app/credit-debit-notes'
      path: '/credit-debit-notes'
      fullPath: '/app/credit-debit-notes'
      preLoaderRoute: typeof AppCreditDebitNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checker': {
      id: '/app/checker'
      path: '/checker'
      fullPath: '/app/checker'
      preLoaderRoute: typeof AppCheckerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bulk-payments': {
      id: '/app/bulk-payments'
      path: '/bulk-payments'
      fullPath: '/app/bulk-payments'
      preLoaderRoute: typeof AppBulkPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/advances': {
      id: '/app/advances'
      path: '/advances'
      fullPath: '/app/advances'
      preLoaderRoute: typeof AppAdvancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounting': {
      id: '/app/accounting'
      path: '/accounting'
      fullPath: '/app/accounting'
      preLoaderRoute: typeof AppAccountingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/': {
      id: '/app/reports/'
      path: '/'
      fullPath: '/app/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/$tab': {
      id: '/app/reports/$tab'
      path: '/$tab'
      fullPath: '/app/reports/$tab'
      preLoaderRoute: typeof AppReportsTabRouteImport
      parentRoute: typeof AppReportsRoute
    }
  }
}

interface AppReportsRouteChildren {
  AppReportsTabRoute: typeof AppReportsTabRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsTabRoute: AppReportsTabRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppRouteChildren {
  AppAccountingRoute: typeof AppAccountingRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAdvancesRoute: typeof AppAdvancesRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppBulkPaymentsRoute: typeof AppBulkPaymentsRoute
  AppCheckerRoute: typeof AppCheckerRoute
  AppCreditDebitNotesRoute: typeof AppCreditDebitNotesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDebtorsRoute: typeof AppDebtorsRoute
  AppDispatchesRoute: typeof AppDispatchesRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppForecastingRoute: typeof AppForecastingRoute
  AppGoodsReceiptsRoute: typeof AppGoodsReceiptsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppProductsRoute: typeof AppProductsRoute
  AppProformasRoute: typeof AppProformasRoute
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppQueueRoute: typeof AppQueueRoute
  AppQuotationsRoute: typeof AppQuotationsRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppSalesOrdersRoute: typeof AppSalesOrdersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppUploadInvoiceRoute: typeof AppUploadInvoiceRoute
  AppVendorsRoute: typeof AppVendorsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountingRoute: AppAccountingRoute,
  AppAdminRoute: AppAdminRoute,
  AppAdvancesRoute: AppAdvancesRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppBulkPaymentsRoute: AppBulkPaymentsRoute,
  AppCheckerRoute: AppCheckerRoute,
  AppCreditDebitNotesRoute: AppCreditDebitNotesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDebtorsRoute: AppDebtorsRoute,
  AppDispatchesRoute: AppDispatchesRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppForecastingRoute: AppForecastingRoute,
  AppGoodsReceiptsRoute: AppGoodsReceiptsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppProductsRoute: AppProductsRoute,
  AppProformasRoute: AppProformasRoute,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppQueueRoute: AppQueueRoute,
  AppQuotationsRoute: AppQuotationsRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppSalesOrdersRoute: AppSalesOrdersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppUploadInvoiceRoute: AppUploadInvoiceRoute,
  AppVendorsRoute: AppVendorsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApprovalsTokenRoute: ApprovalsTokenRoute,
  NoaTokenRoute: NoaTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
