/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoaTokenRouteImport } from './routes/noa.$token'
import { Route as AppVendorsRouteImport } from './routes/app.vendors'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppQueueRouteImport } from './routes/app.queue'
import { Route as AppPurchasesRouteImport } from './routes/app.purchases'
import { Route as AppProformasRouteImport } from './routes/app.proformas'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppDebtorsRouteImport } from './routes/app.debtors'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCheckerRouteImport } from './routes/app.checker'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppAdvancesRouteImport } from './routes/app.advances'
import { Route as AppAdminRouteImport } from './routes/app.admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoaTokenRoute = NoaTokenRouteImport.update({
  id: '/noa/$token',
  path: '/noa/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppProformasRoute = AppProformasRouteImport.update({
  id: '/proformas',
  path: '/proformas',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDebtorsRoute = AppDebtorsRouteImport.update({
  id: '/debtors',
  path: '/debtors',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckerRoute = AppCheckerRouteImport.update({
  id: '/checker',
  path: '/checker',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvancesRoute = AppAdvancesRouteImport.update({
  id: '/advances',
  path: '/advances',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/advances': typeof AppAdvancesRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/checker': typeof AppCheckerRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/debtors': typeof AppDebtorsRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/proformas': typeof AppProformasRoute
  '/app/purchases': typeof AppPurchasesRoute
  '/app/queue': typeof AppQueueRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/vendors': typeof AppVendorsRoute
  '/noa/$token': typeof NoaTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/advances': typeof AppAdvancesRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/checker': typeof AppCheckerRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/debtors': typeof AppDebtorsRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/proformas': typeof AppProformasRoute
  '/app/purchases': typeof AppPurchasesRoute
  '/app/queue': typeof AppQueueRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/vendors': typeof AppVendorsRoute
  '/noa/$token': typeof NoaTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/advances': typeof AppAdvancesRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/checker': typeof AppCheckerRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/debtors': typeof AppDebtorsRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/proformas': typeof AppProformasRoute
  '/app/purchases': typeof AppPurchasesRoute
  '/app/queue': typeof AppQueueRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/vendors': typeof AppVendorsRoute
  '/noa/$token': typeof NoaTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/advances'
    | '/app/alerts'
    | '/app/checker'
    | '/app/dashboard'
    | '/app/debtors'
    | '/app/expenses'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/proformas'
    | '/app/purchases'
    | '/app/queue'
    | '/app/reports'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/vendors'
    | '/noa/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/advances'
    | '/app/alerts'
    | '/app/checker'
    | '/app/dashboard'
    | '/app/debtors'
    | '/app/expenses'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/proformas'
    | '/app/purchases'
    | '/app/queue'
    | '/app/reports'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/vendors'
    | '/noa/$token'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/advances'
    | '/app/alerts'
    | '/app/checker'
    | '/app/dashboard'
    | '/app/debtors'
    | '/app/expenses'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/proformas'
    | '/app/purchases'
    | '/app/queue'
    | '/app/reports'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/vendors'
    | '/noa/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  NoaTokenRoute: typeof NoaTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noa/$token': {
      id: '/noa/$token'
      path: '/noa/$token'
      fullPath: '/noa/$token'
      preLoaderRoute: typeof NoaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/vendors': {
      id: '/app/vendors'
      path: '/vendors'
      fullPath: '/app/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/queue': {
      id: '/app/queue'
      path: '/queue'
      fullPath: '/app/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchases': {
      id: '/app/purchases'
      path: '/purchases'
      fullPath: '/app/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/proformas': {
      id: '/app/proformas'
      path: '/proformas'
      fullPath: '/app/proformas'
      preLoaderRoute: typeof AppProformasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/debtors': {
      id: '/app/debtors'
      path: '/debtors'
      fullPath: '/app/debtors'
      preLoaderRoute: typeof AppDebtorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checker': {
      id: '/app/checker'
      path: '/checker'
      fullPath: '/app/checker'
      preLoaderRoute: typeof AppCheckerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/advances': {
      id: '/app/advances'
      path: '/advances'
      fullPath: '/app/advances'
      preLoaderRoute: typeof AppAdvancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAdvancesRoute: typeof AppAdvancesRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppCheckerRoute: typeof AppCheckerRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDebtorsRoute: typeof AppDebtorsRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppProformasRoute: typeof AppProformasRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppQueueRoute: typeof AppQueueRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppVendorsRoute: typeof AppVendorsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAdvancesRoute: AppAdvancesRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppCheckerRoute: AppCheckerRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDebtorsRoute: AppDebtorsRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppProformasRoute: AppProformasRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppQueueRoute: AppQueueRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppVendorsRoute: AppVendorsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  NoaTokenRoute: NoaTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
